//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.34014
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

	public class Point {
		public int x,y;

		public Point () {
			x = 0;
			y = 0;
		}

		public Point (int posX, int posY){
			x = posX;
			y = posY;
		}
	}
